name: empty_feature_folder
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # flutter bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # google auth
  google_sign_in: ^6.1.4
  # firebase
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.5
  #flutter notifications
  flutter_local_notifications: ^15.1.0+1
  flutter_svg: ^2.0.7
  cloud_firestore: ^4.9.1
  keyboard_dismisser: ^3.0.0
  flutter_credit_card: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true


